import { Product } from './types';

export const categories = [
  'Single Roses',
  'Bouquets',
  'Arrangements',
  'Wedding',
  'Gift Sets',
];

export const categoryTranslations: Record<string, Record<string, string>> = {
  'Single Roses': { en: 'Single Roses', de: 'Einzelne Rosen', hr: 'Pojedinačne ruže', ro: 'Trandafiri singuri', bg: 'Единични рози', tr: 'Tek Güller' },
  'Bouquets': { en: 'Bouquets', de: 'Sträuße', hr: 'Buketi', ro: 'Buchete', bg: 'Букети', tr: 'Buketler' },
  'Arrangements': { en: 'Arrangements', de: 'Arrangements', hr: 'Aranžmani', ro: 'Aranjamente', bg: 'Аранжировки', tr: 'Düzenlemeler' },
  'Wedding': { en: 'Wedding', de: 'Hochzeit', hr: 'Vjenčanje', ro: 'Nuntă', bg: 'Сватба', tr: 'Düğün' },
  'Gift Sets': { en: 'Gift Sets', de: 'Geschenksets', hr: 'Poklon setovi', ro: 'Seturi cadou', bg: 'Подаръчни комплекти', tr: 'Hediye Setleri' },
};

export const colorTranslations: Record<string, Record<string, string>> = {
  'Red': { en: 'Red', de: 'Rot', hr: 'Crvena', ro: 'Roșu', bg: 'Червено', tr: 'Kırmızı' },
  'Cherry Red': { en: 'Cherry Red', de: 'Kirschrot', hr: 'Trešnja crvena', ro: 'Roșu cireș', bg: 'Черешово червено', tr: 'Kiraz Kırmızı' },
  'Dusty Rose': { en: 'Dusty Rose', de: 'Altrosa', hr: 'Prašnjava ruža', ro: 'Trandafir prăfuit', bg: 'Прашна роза', tr: 'Pudra Gülü' },
  'Peach': { en: 'Peach', de: 'Pfirsich', hr: 'Breskva', ro: 'Piersică', bg: 'Праскова', tr: 'Şeftali' },
  'Royal Blue': { en: 'Royal Blue', de: 'Königsblau', hr: 'Kraljevsko plava', ro: 'Albastru regal', bg: 'Кралско синьо', tr: 'Kraliyet Mavisi' },
  'Sunflower Yellow': { en: 'Sunflower Yellow', de: 'Sonnenblumengelb', hr: 'Suncokretno žuta', ro: 'Galben floarea-soarelui', bg: 'Слънчогледово жълто', tr: 'Ayçiçeği Sarısı' },
  'Pink': { en: 'Pink', de: 'Rosa', hr: 'Ružičasta', ro: 'Roz', bg: 'Розово', tr: 'Pembe' },
  'White': { en: 'White', de: 'Weiß', hr: 'Bijela', ro: 'Alb', bg: 'Бяло', tr: 'Beyaz' },
  'Burgundy': { en: 'Burgundy', de: 'Burgund', hr: 'Bordo', ro: 'Burgundy', bg: 'Бордо', tr: 'Bordo' },
  'Lavender': { en: 'Lavender', de: 'Lavendel', hr: 'Lavanda', ro: 'Lavandă', bg: 'Лавандула', tr: 'Lavanta' },
  'Gold': { en: 'Gold', de: 'Gold', hr: 'Zlatna', ro: 'Auriu', bg: 'Златно', tr: 'Altın' },
  'Ivory': { en: 'Ivory', de: 'Elfenbein', hr: 'Bjelokost', ro: 'Ivoriu', bg: 'Слонова кост', tr: 'Fildişi' },
  'Coral': { en: 'Coral', de: 'Koralle', hr: 'Koraljna', ro: 'Coral', bg: 'Корал', tr: 'Mercan' },
  'Mixed': { en: 'Mixed', de: 'Gemischt', hr: 'Mješovito', ro: 'Mixt', bg: 'Смесени', tr: 'Karışık' },
  'Blue': { en: 'Blue', de: 'Blau', hr: 'Plava', ro: 'Albastru', bg: 'Синьо', tr: 'Mavi' },
};

export const products: Product[] = [
  {
    id: '1',
    slug: 'classic-red-satin-rose',
    price: 15.00,
    images: ['/products/rose-red.jpg'],
    category: 'Single Roses',
    colors: ['Red'],
    inStock: true,
    featured: true,
    name: {
      en: 'Classic Red Satin Rose',
      de: 'Klassische rote Satinrose',
      hr: 'Klasična crvena satenska ruža',
      ro: 'Trandafir clasic roșu din satin',
      bg: 'Класическа червена сатенена роза',
      tr: 'Klasik Kırmızı Saten Gül',
    },
    description: {
      en: 'A timeless classic — our signature red satin rose, handcrafted with premium satin fabric. Perfect as a gift or home decoration. Each petal is individually shaped to create a lifelike, stunning bloom that will last forever.',
      de: 'Ein zeitloser Klassiker — unsere charakteristische rote Satinrose, handgefertigt aus Premium-Satinstoff. Perfekt als Geschenk oder Heimdekoration.',
      hr: 'Bezvremenski klasik — naša prepoznatljiva crvena satenska ruža, ručno izrađena od premium satenske tkanine. Savršena kao poklon ili ukras za dom.',
      ro: 'Un clasic atemporal — trandafirul nostru roșu din satin, lucrat manual din material satin premium. Perfect ca cadou sau decorațiune pentru casă.',
      bg: 'Безвременна класика — нашата емблематична червена сатенена роза, ръчно изработена от премиум сатенена тъкан. Перфектна като подарък или домашна декорация.',
      tr: 'Zamansız bir klasik — premium saten kumaştan el yapımı imza kırmızı saten gülümüz. Hediye veya ev dekorasyonu olarak mükemmel.',
    },
    shortDescription: {
      en: 'Timeless handcrafted red satin rose — a perfect gift that lasts forever.',
      de: 'Zeitlose handgefertigte rote Satinrose — ein perfektes Geschenk für die Ewigkeit.',
      hr: 'Bezvremenski ručno izrađena crvena satenska ruža — savršen poklon koji traje zauvijek.',
      ro: 'Trandafir clasic roșu din satin — un cadou perfect care durează o veșnicie.',
      bg: 'Безвременна ръчно изработена червена сатенена роза — перфектен подарък за вечността.',
      tr: 'Zamansız el yapımı kırmızı saten gül — sonsuza kadar süren mükemmel bir hediye.',
    },
  },
  {
    id: '2',
    slug: 'blush-pink-satin-rose',
    price: 15.00,
    images: ['/products/rose-pink.jpg'],
    category: 'Single Roses',
    colors: ['Pink'],
    inStock: true,
    featured: true,
    name: {
      en: 'Blush Pink Satin Rose',
      de: 'Zartrosa Satinrose',
      hr: 'Ružičasta satenska ruža',
      ro: 'Trandafir roz din satin',
      bg: 'Розова сатенена роза',
      tr: 'Pudra Pembe Saten Gül',
    },
    description: {
      en: 'Delicate and romantic, this blush pink satin rose captures the softness of spring. Handcrafted with care, it makes a beautiful addition to any room or a thoughtful gift for someone special.',
      de: 'Zart und romantisch, diese zartrosa Satinrose fängt die Weichheit des Frühlings ein. Mit Sorgfalt handgefertigt.',
      hr: 'Nježna i romantična, ova ružičasta satenska ruža hvata mekoću proljeća. Ručno izrađena s pažnjom.',
      ro: 'Delicată și romantică, acest trandafir roz din satin surprinde delicatețea primăverii. Lucrat manual cu grijă.',
      bg: 'Деликатна и романтична, тази розова сатенена роза улавя нежността на пролетта. Ръчно изработена с грижа.',
      tr: 'Zarif ve romantik, bu pudra pembe saten gül baharın yumuşaklığını yakalar. Özenle el yapımı.',
    },
    shortDescription: {
      en: 'Romantic blush pink satin rose — soft, elegant, and everlasting.',
      de: 'Romantische zartrosa Satinrose — weich, elegant und ewig.',
      hr: 'Romantična ružičasta satenska ruža — nježna, elegantna i vječna.',
      ro: 'Trandafir romantic roz din satin — delicat, elegant și veșnic.',
      bg: 'Романтична розова сатенена роза — нежна, елегантна и вечна.',
      tr: 'Romantik pudra pembe saten gül — yumuşak, zarif ve sonsuz.',
    },
  },
  {
    id: '3',
    slug: 'ivory-white-satin-rose',
    price: 15.00,
    images: ['/products/rose-white.jpg'],
    category: 'Single Roses',
    colors: ['White', 'Ivory'],
    inStock: true,
    featured: false,
    name: {
      en: 'Ivory White Satin Rose',
      de: 'Elfenbeinweiße Satinrose',
      hr: 'Bjelokosna bijela satenska ruža',
      ro: 'Trandafir alb ivoriu din satin',
      bg: 'Бяла сатенена роза цвят слонова кост',
      tr: 'Fildişi Beyaz Saten Gül',
    },
    description: {
      en: 'Pure and sophisticated, this ivory white satin rose embodies elegance. Perfect for weddings, special occasions, or as a timeless home accent piece.',
      de: 'Rein und anspruchsvoll, diese elfenbeinweiße Satinrose verkörpert Eleganz. Perfekt für Hochzeiten und besondere Anlässe.',
      hr: 'Čista i sofisticirana, ova bjelokosna bijela satenska ruža utjelovljuje eleganciju. Savršena za vjenčanja i posebne prilike.',
      ro: 'Pură și sofisticată, acest trandafir alb ivoriu din satin întruchipează eleganța. Perfect pentru nunți și ocazii speciale.',
      bg: 'Чиста и изтънчена, тази бяла сатенена роза олицетворява елегантността. Перфектна за сватби и специални поводи.',
      tr: 'Saf ve sofistike, bu fildişi beyaz saten gül zarafeti somutlaştırır. Düğünler ve özel günler için mükemmel.',
    },
    shortDescription: {
      en: 'Pure ivory white satin rose — elegance that lasts a lifetime.',
      de: 'Reine elfenbeinweiße Satinrose — Eleganz, die ein Leben lang hält.',
      hr: 'Čista bjelokosna bijela satenska ruža — elegancija koja traje cijeli život.',
      ro: 'Trandafir alb ivoriu din satin — eleganță care durează o viață.',
      bg: 'Чиста бяла сатенена роза — елегантност, която трае цял живот.',
      tr: 'Saf fildişi beyaz saten gül — ömür boyu süren zarafet.',
    },
  },
  {
    id: '4',
    slug: 'romantic-rose-bouquet',
    price: 45.00,
    images: ['/products/bouquet-romantic.jpg'],
    category: 'Bouquets',
    colors: ['Red', 'Pink'],
    inStock: true,
    featured: true,
    name: {
      en: 'Romantic Rose Bouquet',
      de: 'Romantischer Rosenstrauß',
      hr: 'Romantični buket ruža',
      ro: 'Buchet romantic de trandafiri',
      bg: 'Романтичен букет от рози',
      tr: 'Romantik Gül Buketi',
    },
    description: {
      en: 'A stunning bouquet of 5 handcrafted satin roses in shades of red and pink. This romantic arrangement makes the perfect gift for anniversaries, Valentine\'s Day, or any occasion that calls for love.',
      de: 'Ein atemberaubender Strauß aus 5 handgefertigten Satinrosen in Rot- und Rosatönen. Perfekt für Jahrestage und den Valentinstag.',
      hr: 'Prekrasan buket od 5 ručno izrađenih satenskih ruža u nijansama crvene i ružičaste. Savršen poklon za godišnjice i Valentinovo.',
      ro: 'Un buchet uimitor de 5 trandafiri din satin în nuanțe de roșu și roz. Perfect pentru aniversări și Ziua Îndrăgostiților.',
      bg: 'Зашеметяващ букет от 5 ръчно изработени сатенени рози в нюанси на червено и розово. Перфектен за годишнини и Свети Валентин.',
      tr: 'Kırmızı ve pembe tonlarında 5 el yapımı saten gülden oluşan muhteşem bir buket. Yıldönümleri ve Sevgililer Günü için mükemmel.',
    },
    shortDescription: {
      en: 'Bouquet of 5 satin roses in red & pink — the perfect romantic gift.',
      de: 'Strauß aus 5 Satinrosen in Rot & Rosa — das perfekte romantische Geschenk.',
      hr: 'Buket od 5 satenskih ruža u crvenoj i ružičastoj — savršen romantični poklon.',
      ro: 'Buchet de 5 trandafiri din satin roșu și roz — cadoul romantic perfect.',
      bg: 'Букет от 5 сатенени рози в червено и розово — перфектният романтичен подарък.',
      tr: 'Kırmızı ve pembe 5 saten gülden buket — mükemmel romantik hediye.',
    },
  },
  {
    id: '5',
    slug: 'pastel-dream-bouquet',
    price: 55.00,
    images: ['/products/bouquet-pastel.jpg'],
    category: 'Bouquets',
    colors: ['Pink', 'Peach', 'Lavender'],
    inStock: true,
    featured: true,
    name: {
      en: 'Pastel Dream Bouquet',
      de: 'Pastelltraum-Strauß',
      hr: 'Pastelni buket snova',
      ro: 'Buchet de vis pastel',
      bg: 'Пастелен букет мечта',
      tr: 'Pastel Rüya Buketi',
    },
    description: {
      en: 'A dreamy bouquet of 7 satin roses in soft pastel shades of pink, peach, and lavender. This ethereal arrangement brings a touch of spring into any space.',
      de: 'Ein traumhafter Strauß aus 7 Satinrosen in sanften Pastelltönen von Rosa, Pfirsich und Lavendel.',
      hr: 'Sanjivi buket od 7 satenskih ruža u nježnim pastelnim nijansama ružičaste, breskve i lavande.',
      ro: 'Un buchet de vis de 7 trandafiri din satin în nuanțe pastelate de roz, piersică și lavandă.',
      bg: 'Мечтан букет от 7 сатенени рози в нежни пастелни нюанси на розово, праскова и лавандула.',
      tr: 'Pembe, şeftali ve lavanta tonlarında 7 saten gülden oluşan rüya gibi bir buket.',
    },
    shortDescription: {
      en: 'Dreamy bouquet of 7 pastel satin roses — pink, peach & lavender.',
      de: 'Traumhafter Strauß aus 7 pastellfarbenen Satinrosen.',
      hr: 'Sanjivi buket od 7 pastelnih satenskih ruža.',
      ro: 'Buchet de vis de 7 trandafiri din satin pastel.',
      bg: 'Мечтан букет от 7 пастелни сатенени рози.',
      tr: 'Pastel tonlarda 7 saten gülden rüya gibi buket.',
    },
  },
  {
    id: '6',
    slug: 'luxury-burgundy-arrangement',
    price: 75.00,
    images: ['/products/arrangement-burgundy.jpg'],
    category: 'Arrangements',
    colors: ['Burgundy', 'Gold'],
    inStock: true,
    featured: true,
    name: {
      en: 'Luxury Burgundy & Gold Arrangement',
      de: 'Luxus Burgund & Gold Arrangement',
      hr: 'Luksuzni bordo i zlatni aranžman',
      ro: 'Aranjament de lux burgundy și auriu',
      bg: 'Луксозна аранжировка в бордо и златно',
      tr: 'Lüks Bordo & Altın Düzenleme',
    },
    description: {
      en: 'An opulent arrangement featuring burgundy and gold satin roses in an elegant display. This luxurious piece makes a stunning centerpiece for any table or mantelpiece.',
      de: 'Ein opulentes Arrangement mit Burgund- und Gold-Satinrosen in einer eleganten Präsentation.',
      hr: 'Raskošan aranžman s bordo i zlatnim satenskim ružama u elegantnom prikazu.',
      ro: 'Un aranjament opulent cu trandafiri din satin burgundy și auriu într-o prezentare elegantă.',
      bg: 'Разкошна аранжировка с бордо и златни сатенени рози в елегантна презентация.',
      tr: 'Zarif bir sunumda bordo ve altın saten güller içeren gösterişli bir düzenleme.',
    },
    shortDescription: {
      en: 'Opulent burgundy & gold satin rose arrangement — pure luxury.',
      de: 'Opulentes Burgund & Gold Satinrosen-Arrangement — purer Luxus.',
      hr: 'Raskošan bordo i zlatni aranžman satenskih ruža — čisti luksuz.',
      ro: 'Aranjament opulent de trandafiri burgundy și auriu — lux pur.',
      bg: 'Разкошна аранжировка в бордо и златно — чист лукс.',
      tr: 'Gösterişli bordo ve altın saten gül düzenlemesi — saf lüks.',
    },
  },
  {
    id: '7',
    slug: 'bridal-white-bouquet',
    price: 89.00,
    images: ['/products/wedding-bridal.jpg'],
    category: 'Wedding',
    colors: ['White', 'Ivory'],
    inStock: true,
    featured: false,
    name: {
      en: 'Bridal White Bouquet',
      de: 'Brautstrauß in Weiß',
      hr: 'Mladenkin bijeli buket',
      ro: 'Buchet de mireasă alb',
      bg: 'Булчински бял букет',
      tr: 'Gelin Beyaz Buketi',
    },
    description: {
      en: 'An exquisite bridal bouquet of white and ivory satin roses, designed to complement any wedding dress. This keepsake bouquet will be a treasured memento of your special day.',
      de: 'Ein exquisiter Brautstrauß aus weißen und elfenbeinfarbenen Satinrosen, der jedes Brautkleid ergänzt.',
      hr: 'Izvrstan mladenkin buket od bijelih i bjelokosnih satenskih ruža, dizajniran da nadopuni svaku vjenčanicu.',
      ro: 'Un buchet de mireasă exquisit din trandafiri albi și ivoriu din satin, conceput să completeze orice rochie de mireasă.',
      bg: 'Изискан булчински букет от бели и кремави сатенени рози, проектиран да допълни всяка сватбена рокля.',
      tr: 'Her gelinliği tamamlamak için tasarlanmış beyaz ve fildişi saten güllerden oluşan zarif bir gelin buketi.',
    },
    shortDescription: {
      en: 'Exquisite bridal bouquet — a keepsake for your special day.',
      de: 'Exquisiter Brautstrauß — ein Andenken für Ihren besonderen Tag.',
      hr: 'Izvrstan mladenkin buket — uspomena na vaš poseban dan.',
      ro: 'Buchet de mireasă exquisit — o amintire pentru ziua dvs. specială.',
      bg: 'Изискан булчински букет — спомен за вашия специален ден.',
      tr: 'Zarif gelin buketi — özel gününüz için bir hatıra.',
    },
  },
  {
    id: '8',
    slug: 'rose-gift-box',
    price: 35.00,
    images: ['/products/gift-box.jpg'],
    category: 'Gift Sets',
    colors: ['Red', 'Pink', 'White'],
    inStock: true,
    featured: false,
    name: {
      en: 'Satin Rose Gift Box',
      de: 'Satinrosen-Geschenkbox',
      hr: 'Poklon kutija satenskih ruža',
      ro: 'Cutie cadou cu trandafiri din satin',
      bg: 'Подаръчна кутия със сатенени рози',
      tr: 'Saten Gül Hediye Kutusu',
    },
    description: {
      en: 'A beautifully presented gift box containing 3 satin roses in red, pink, and white. Comes in an elegant box with ribbon — ready to gift. The perfect present for birthdays, Mother\'s Day, or just because.',
      de: 'Eine wunderschön präsentierte Geschenkbox mit 3 Satinrosen in Rot, Rosa und Weiß. Kommt in einer eleganten Box mit Schleife.',
      hr: 'Prekrasno prezentirana poklon kutija s 3 satenske ruže u crvenoj, ružičastoj i bijeloj. Dolazi u elegantnoj kutiji s vrpcom.',
      ro: 'O cutie cadou frumos prezentată cu 3 trandafiri din satin în roșu, roz și alb. Vine într-o cutie elegantă cu panglică.',
      bg: 'Красиво представена подаръчна кутия с 3 сатенени рози в червено, розово и бяло. Идва в елегантна кутия с панделка.',
      tr: 'Kırmızı, pembe ve beyaz 3 saten gül içeren güzel bir hediye kutusu. Kurdeleli zarif kutuda gelir.',
    },
    shortDescription: {
      en: 'Gift box with 3 satin roses — beautifully packaged and ready to give.',
      de: 'Geschenkbox mit 3 Satinrosen — schön verpackt und geschenkfertig.',
      hr: 'Poklon kutija s 3 satenske ruže — lijepo pakirana i spremna za poklanjanje.',
      ro: 'Cutie cadou cu 3 trandafiri din satin — frumos ambalată și gata de oferit.',
      bg: 'Подаръчна кутия с 3 сатенени рози — красиво опакована и готова за подаряване.',
      tr: 'Hediye kutusu ile 3 saten gül — güzelce paketlenmiş ve hediye etmeye hazır.',
    },
  },
  {
    id: '9',
    slug: 'coral-sunset-rose',
    price: 15.00,
    images: ['/products/rose-coral.jpg'],
    category: 'Single Roses',
    colors: ['Coral'],
    inStock: true,
    featured: false,
    name: {
      en: 'Coral Sunset Rose',
      de: 'Korallen-Sonnenuntergangsrose',
      hr: 'Koraljno-narančasta ruža zalaska sunca',
      ro: 'Trandafir coral apus de soare',
      bg: 'Коралова роза залез',
      tr: 'Mercan Gün Batımı Gülü',
    },
    description: {
      en: 'Warm and vibrant, this coral satin rose captures the beauty of a summer sunset. A unique and eye-catching piece that adds warmth to any space.',
      de: 'Warm und lebendig, diese korallfarbene Satinrose fängt die Schönheit eines Sommerabends ein.',
      hr: 'Topla i živahna, ova koraljno satenska ruža hvata ljepotu ljetnog zalaska sunca.',
      ro: 'Cald și vibrant, acest trandafir coral din satin surprinde frumusețea unui apus de vară.',
      bg: 'Топла и жизнена, тази коралова сатенена роза улавя красотата на летен залез.',
      tr: 'Sıcak ve canlı, bu mercan saten gül bir yaz gün batımının güzelliğini yakalar.',
    },
    shortDescription: {
      en: 'Vibrant coral satin rose — capturing the warmth of a sunset.',
      de: 'Lebhafte korallfarbene Satinrose — die Wärme eines Sonnenuntergangs.',
      hr: 'Živahna koraljno satenska ruža — toplina zalaska sunca.',
      ro: 'Trandafir coral vibrant din satin — căldura unui apus de soare.',
      bg: 'Жизнена коралова сатенена роза — топлината на залеза.',
      tr: 'Canlı mercan saten gül — gün batımının sıcaklığı.',
    },
  },
  {
    id: '10',
    slug: 'lavender-dream-rose',
    price: 15.00,
    images: ['/products/rose-lavender.jpg'],
    category: 'Single Roses',
    colors: ['Lavender'],
    inStock: true,
    featured: false,
    name: {
      en: 'Lavender Dream Rose',
      de: 'Lavendel-Traumrose',
      hr: 'Lavanda ruža snova',
      ro: 'Trandafir de vis lavandă',
      bg: 'Лавандулова роза мечта',
      tr: 'Lavanta Rüya Gülü',
    },
    description: {
      en: 'Enchanting and unique, this lavender satin rose brings a touch of magic to any setting. Its soft purple hue creates a calming, elegant atmosphere.',
      de: 'Bezaubernd und einzigartig, diese Lavendel-Satinrose bringt einen Hauch von Magie in jede Umgebung.',
      hr: 'Očaravajuća i jedinstvena, ova lavanda satenska ruža donosi dodir magije u svaki prostor.',
      ro: 'Fermecător și unic, acest trandafir lavandă din satin aduce o notă de magie în orice decor.',
      bg: 'Очарователна и уникална, тази лавандулова сатенена роза внася магия във всяка обстановка.',
      tr: 'Büyüleyici ve benzersiz, bu lavanta saten gül her ortama bir dokunuş sihir katar.',
    },
    shortDescription: {
      en: 'Enchanting lavender satin rose — a touch of magic.',
      de: 'Bezaubernde Lavendel-Satinrose — ein Hauch von Magie.',
      hr: 'Očaravajuća lavanda satenska ruža — dodir magije.',
      ro: 'Trandafir fermecător lavandă din satin — o notă de magie.',
      bg: 'Очарователна лавандулова сатенена роза — докосване на магия.',
      tr: 'Büyüleyici lavanta saten gül — bir dokunuş sihir.',
    },
  },
  {
    id: '11',
    slug: 'mixed-garden-arrangement',
    price: 65.00,
    images: ['/products/arrangement-mixed.jpg'],
    category: 'Arrangements',
    colors: ['Mixed'],
    inStock: true,
    featured: false,
    name: {
      en: 'Mixed Garden Arrangement',
      de: 'Gemischtes Garten-Arrangement',
      hr: 'Mješoviti vrtni aranžman',
      ro: 'Aranjament de grădină mixt',
      bg: 'Смесена градинска аранжировка',
      tr: 'Karışık Bahçe Düzenlemesi',
    },
    description: {
      en: 'A vibrant arrangement of mixed satin roses in various colors, reminiscent of a beautiful garden in full bloom. Features roses in red, pink, white, and peach.',
      de: 'Ein lebhaftes Arrangement aus gemischten Satinrosen in verschiedenen Farben, das an einen blühenden Garten erinnert.',
      hr: 'Živahan aranžman mješovitih satenskih ruža u raznim bojama, koji podsjeća na prekrasan vrt u punom cvatu.',
      ro: 'Un aranjament vibrant de trandafiri din satin în diverse culori, amintind de o grădină frumoasă în plină înflorire.',
      bg: 'Жизнена аранжировка от смесени сатенени рози в различни цветове, напомняща красива градина в пълен разцвет.',
      tr: 'Tam çiçeklenmiş güzel bir bahçeyi andıran çeşitli renklerde karışık saten güllerden canlı bir düzenleme.',
    },
    shortDescription: {
      en: 'Vibrant mixed satin rose arrangement — a garden in bloom.',
      de: 'Lebhaftes gemischtes Satinrosen-Arrangement — ein blühender Garten.',
      hr: 'Živahan mješoviti aranžman satenskih ruža — vrt u cvatu.',
      ro: 'Aranjament vibrant mixt de trandafiri din satin — o grădină în floare.',
      bg: 'Жизнена смесена аранжировка от сатенени рози — градина в разцвет.',
      tr: 'Canlı karışık saten gül düzenlemesi — çiçek açan bir bahçe.',
    },
  },
  {
    id: '12',
    slug: 'wedding-table-centerpiece',
    price: 95.00,
    images: ['/products/wedding-centerpiece.jpg'],
    category: 'Wedding',
    colors: ['White', 'Ivory', 'Gold'],
    inStock: true,
    featured: false,
    name: {
      en: 'Wedding Table Centerpiece',
      de: 'Hochzeits-Tischdekoration',
      hr: 'Vjenčani stolni ukras',
      ro: 'Centru de masă pentru nuntă',
      bg: 'Сватбена декорация за маса',
      tr: 'Düğün Masası Süslemesi',
    },
    description: {
      en: 'An elegant wedding table centerpiece featuring white, ivory, and gold satin roses. Designed to add a touch of luxury to your reception tables. Custom orders available for matching your wedding color scheme.',
      de: 'Eine elegante Hochzeits-Tischdekoration mit weißen, elfenbeinfarbenen und goldenen Satinrosen.',
      hr: 'Elegantan vjenčani stolni ukras s bijelim, bjelokosnim i zlatnim satenskim ružama.',
      ro: 'Un centru de masă elegant pentru nuntă cu trandafiri albi, ivoriu și aurii din satin.',
      bg: 'Елегантна сватбена декорация за маса с бели, кремави и златни сатенени рози.',
      tr: 'Beyaz, fildişi ve altın saten güllerden oluşan zarif düğün masası süslemesi.',
    },
    shortDescription: {
      en: 'Elegant wedding centerpiece — white, ivory & gold satin roses.',
      de: 'Elegante Hochzeits-Tischdekoration — weiße, elfenbeinfarbene & goldene Satinrosen.',
      hr: 'Elegantan vjenčani stolni ukras — bijele, bjelokosne i zlatne satenske ruže.',
      ro: 'Centru de masă elegant — trandafiri albi, ivoriu și aurii din satin.',
      bg: 'Елегантна сватбена декорация — бели, кремави и златни сатенени рози.',
      tr: 'Zarif düğün süslemesi — beyaz, fildişi ve altın saten güller.',
    },
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.featured);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return products;
  return products.filter(p => p.category === category);
}

export function getRelatedProducts(product: Product, limit: number = 4): Product[] {
  return products
    .filter(p => p.id !== product.id && (p.category === product.category || p.colors.some(c => product.colors.includes(c))))
    .slice(0, limit);
}
